#!/bin/bash
#
# Usage: ./helper ....

# These lines taken from https://stackoverflow.com/a/1638397
# Absolute path to this script, e.g. /home/user/pi/EosRemote/ssl/helper
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/pi/EosRemote/ssl
SCRIPTPATH=$(dirname "$SCRIPT")

SSL_DIR=${SCRIPTPATH}
CA_DIR=${SSL_DIR}/CA

usage() {
  echo "Usage: $0 server|CA|help [option]"
}

help() {
  usage
  echo
  echo "Help text"
  echo
  echo "SCRIPT =     '${SCRIPT}'"
  echo "SCRIPTPATH = '${SCRIPTPATH}'"
}

server_usage() {
  echo "Usage: $0 server newkey|update|show|enddate|help"
}

server_help() {
  server_usage
  echo
  echo "server newkey   Creates a new RSA key for the server"
  echo "server update   Creates a new certificate for the server, from the key"
  echo "server show     Show the details of the server certificate"
  echo "server enddate  Show the expiry date/time of the server certificate"
}

server_newkey() {
  openssl genrsa -out $SSL_DIR/server-key.pem 2048
}

server_update() {
  echo "Create a new Certificate Request with existing Key..."
  openssl req -new -key $SSL_DIR/server-key.pem -out $SSL_DIR/server-csr.pem -config $SSL_DIR/server-openssl.cnf
  echo "Use our CA to sign the Certificate Request..."
  # -batch  prevents openssl asking if we want to sign the certificate, and commit
  # -notext prevents the plain text details being included in the pem file
  # -create_serial creates the serial number file if it doesn't exist
  openssl ca -in $SSL_DIR/server-csr.pem -out $SSL_DIR/server-cert.pem -batch -create_serial -config $SSL_DIR/ca-openssl.cnf
  echo "...done!"
}

server_show() {
  openssl x509 -in $SSL_DIR/server-cert.pem -noout -text
}

server_enddate() {
  local when=$(openssl x509 -in $SSL_DIR/server-cert.pem -noout -enddate)
  echo "Expiry date/time: ${when:9}"
}

server() {
  # echo "Server"
  case $1 in
    update)
      server_update
      ;;
    newKey|newkey|new_key)
      server_newkey
      ;;
    show)
      server_show
      ;;
    enddate)
      server_enddate
      ;;
    help)
      server_help
      ;;
    *)
      server_usage
      exit 1
      ;;
  esac
}

ca() {
  echo "CA"
}

case $1 in
  server)
    server $2
    ;;
  CA|ca|Ca|cA)
    ca $2
    ;;
  help)
    help
    ;;
  *)
    usage
    exit 1
    ;;
esac